#ifndef HARDWARE_CONSTANTS_H_INCLUDED
#define HARDWARE_CONSTANTS_H_INCLUDED

#define NUMBER_OF_DRAWNERS 9
#define NUMBER_OF_OUTPUTS_REGISTER 8

// Front panel pins
#define POWER_LED 26
#define STATUS_LED_RED 15
#define STATUS_LED_GREEN 2
#define STATUS_LED_BLUE 4
#define RESET_BUTTON 39

// Register pins
#define REGISTER_CLEAR 27
#define REGISTER_CLOCK 14
#define REGISTER_2_INPUT 12
#define REGISTER_1_INPUT 13

// Multiplex pins
#define SENSOR_INPUT 36
#define MULTIPLEX_SELECTOR_BIT_0 16
#define MULTIPLEX_SELECTOR_BIT_1 17
#define MULTIPLEX_SELECTOR_BIT_2 5
#define MULTIPLEX_SELECTOR_BIT_3 18 

#endif